# Generated by Django 6.0.2 on 2026-02-28 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Director'), ('member', 'Member')], default='member', max_length=20)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Subactivitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True)),
                ('livrabil', models.CharField(choices=[('cod', 'Cod'), ('raport', 'Raport'), ('prezentare', 'Prezentare'), ('documentatie', 'Documentație'), ('altul', 'Altul')], max_length=20)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subactivitati', to='api.lab')),
            ],
            options={
                'unique_together': {('lab', 'nume')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('monthly_hour_limit', models.IntegerField(default=40)),
                ('labs', models.ManyToManyField(blank=True, through='api.LabMembership', to='api.lab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='labmembership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('nr_ore', models.IntegerField()),
                ('durata', models.CharField(max_length=20)),
                ('activity_description', models.TextField()),
                ('comentarii', models.TextField(blank=True)),
                ('links', models.TextField(blank=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lab')),
                ('subactivitate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subactivitate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='labmembership',
            unique_together={('profile', 'lab')},
        ),
    ]
