# Generated by Django 6.0.2 on 2026-03-01 12:30

from django.db import migrations, models
def copy_limits(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    LabMembership = apps.get_model("api", "LabMembership")

    for membership in LabMembership.objects.all():
        membership.monthly_hour_limit = membership.profile.monthly_hour_limit
        membership.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmembership',
            name='monthly_hour_limit',
            field=models.IntegerField(default=40),
        ),
        migrations.RunPython(copy_limits),
    ]
