# Generated by Django 6.0.2 on 2026-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_labmembership_monthly_hour_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactivitate',
            name='livrabil',
            field=models.CharField(blank=True, choices=[('cod', 'Cod'), ('raport', 'Raport'), ('prezentare', 'Prezentare'), ('documentatie', 'Documentație'), ('altul', 'Altul')], max_length=20, null=True),
        ),
    ]
