# Generated by Django 6.0.2 on 2026-03-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subactivitate_livrabil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subactivitate',
            name='livrabil',
        ),
        migrations.AddField(
            model_name='workentry',
            name='livrabil',
            field=models.CharField(choices=[('cod', 'Cod'), ('raport', 'Raport'), ('prezentare', 'Prezentare'), ('documentatie', 'Documentație'), ('altul', 'Altul')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
