# Generated by Django 6.0.2 on 2026-03-08 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_subactivitate_livrabil_workentry_livrabil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='shared_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
