# Generated by Django 6.0.2 on 2026-03-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workentry_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workentry',
            name='subactivitate',
        ),
        migrations.DeleteModel(
            name='Subactivitate',
        ),
    ]
