# Generated by Django 6.0.2 on 2026-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workentry_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workentry',
            name='livrabil',
            field=models.TextField(),
        ),
    ]
