# Generated by Django 6.0.2 on 2026-03-12 12:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_workentry_activitate(apps, schema_editor):
    """
    Existing WorkEntry rows predate the Activitate FK. Add a per-lab placeholder
    Activitate and attach legacy rows to it so we can enforce NOT NULL.
    """
    Activitate = apps.get_model("api", "Activitate")
    WorkEntry = apps.get_model("api", "WorkEntry")
    Lab = apps.get_model("api", "Lab")

    legacy_name = "Neclasificat"
    legacy_descriere = "Auto-created during migration for existing work entries."

    lab_ids = (
        WorkEntry.objects.filter(activitate__isnull=True)
        .values_list("lab_id", flat=True)
        .distinct()
    )

    for lab_id in lab_ids:
        lab = Lab.objects.get(id=lab_id)
        activitate, _ = Activitate.objects.get_or_create(
            lab=lab,
            nume=legacy_name,
            defaults={"descriere": legacy_descriere},
        )
        WorkEntry.objects.filter(lab_id=lab_id, activitate__isnull=True).update(
            activitate_id=activitate.id
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_workentry_subactivitate_delete_subactivitate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitati', to='api.lab')),
            ],
            options={
                'unique_together': {('lab', 'nume')},
            },
        ),
        migrations.AddField(
            model_name='workentry',
            name='activitate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.activitate'),
        ),
        migrations.RunPython(backfill_workentry_activitate, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workentry',
            name='activitate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.activitate'),
        ),
    ]
