# Generated by Django 6.0.2 on 2026-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_activitate_workentry_activitate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='jurnal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='livrabil',
            field=models.TextField(blank=True, default=''),
        ),
    ]
