# Generated by Django 6.0.2 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_workentry_jurnal_alter_workentry_livrabil"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitate",
            name="denumire_activitate",
            field=models.TextField(blank=True, default=""),
        ),
    ]

