# Generated by Django 6.0.2 on 2026-03-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_activitate_denumire_activitate"),
    ]

    operations = [
        migrations.AddField(
            model_name="workentry",
            name="scurta_descriere_jurnal",
            field=models.TextField(blank=True, default=""),
        ),
    ]

