# Generated by Django 6.0.2 on 2026-03-28 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lab_titlu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('livrabil', models.TextField(blank=True, default='')),
                ('comentarii', models.TextField(blank=True, default='')),
                ('links', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activitate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.activitate')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lab', 'activitate', 'year', 'month')},
            },
        ),
    ]
