# Generated by Django 6.0.2 on 2026-05-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_move_user_id_code_to_labmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='responsabil_aumovio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
